//------------------------------------------------------------------------------
//        This code was generated by myriad.
//        Changes to this file will be lost when the code is regenerated.
//------------------------------------------------------------------------------
namespace rec Program

open EffectsPoc
type ILoggingServiceProvider =
    abstract LoggingService: ILoggingService

module LoggingService =
    let log a =
        Effect.Create(fun (env: #ILoggingServiceProvider) -> env.LoggingService.Log(a))
namespace rec Program

open EffectsPoc
type IConsoleServiceProvider =
    abstract ConsoleService: IConsoleService

module ConsoleService =
    let writeLine a =
        Effect.Create(fun (env: #IConsoleServiceProvider) -> env.ConsoleService.WriteLine(a))

    let readLine () =
        Effect.Create(fun (env: #IConsoleServiceProvider) -> env.ConsoleService.ReadLine())
namespace rec Program

open EffectsPoc
type IPersistenceServiceProvider =
    abstract PersistenceService: IPersistenceService

module PersistenceService =
    let persist a =
        Effect.Create(fun (env: #IPersistenceServiceProvider) -> env.PersistenceService.Persist(a))
